# Setup
baseurl:          ""
auxtoro: Auxtoro
# ŝanĝu eo al via lingvo se vi ne laboras rekte en esperanto
laborlingvo: eo
# malkomentigu la sekvan linion por forigi la menuon "ĉiuj afiŝoj"
#ne_afisxoj: "true"
# malkomentigu la sekvan linion por forigi la menuon "serĉu per google"
#ne_googlesearch: "true"
permesilo: 


# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

exclude: [ _locale , _scripts , "*.backup", "*.bak" , "??/_data", _traduko.jar]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
