# Setup
baseurl:          ""
auxtoro: Auxtoro
# ŝanĝu eo al via lingvo se vi ne laboras rekte en esperanto
laborlingvo: eo
# malkomentigu la sekvan linion por forigi la menuon "ĉiuj afiŝoj"
#ne_afisxoj: "true"
# malkomentigu la sekvan linion por forigi la menuon "serĉu per google"
#ne_googlesearch: "true"
permesilo: "<a href=https://creativecommons.org/licenses/by-sa/3.0/deed.eo>CC BY-SA 3.0</a>"


# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

exclude: [ _locale , _scripts , "*.backup", "*.bak" ]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
